#!/usr/bin/env perl

# script by enghui yap
# PROLID interface design probe placement
#
# given coordinates Pm (mesh) and Pr (closest receptor heavy atom to this mesh), 
# compute nPos-size array of coordinates for PNs,P2s,PCs of the middle residue of the probe
# PNs and PCs are generated by rotated about the v1r_normed axis
#
#          (base)
#    PN o----CA----o PC
#         bl  |  bl
#             |   
#             | 3*bondlength (estimate)
#             |   
#          P2 o (FA1)
#             |
#             | 1*bondlength
#             |
#          Pm o (FA)
#             |
#             | v1r_normed    
#             | 
# ------------o-------------- (receptor surface)
#             Pr

use strict;
use Benchmark;
use POSIX;
use lib $ENV{'PROTLIDv1HOME'}."/scripts/MYPERLPM";
use myVectors;

# main program
(@ARGV==8) || die("Usage: [xm] [ym] [zm] [xr] [yr] [zr] [bondlength] [nPos]\n") ;

my @Pm = ($ARGV[0],$ARGV[1],$ARGV[2]);
my @Pr = ($ARGV[3],$ARGV[4],$ARGV[5]);
my $bondlength = $ARGV[6];
my $nPos = $ARGV[7];
my $angle_inc  = floor(360/$nPos);

# normalized vector from rec to mesh
my @v1r_normed = ( $Pm[0]-$Pr[0], $Pm[1]-$Pr[1], $Pm[2]-$Pr[2]);
_normalize( \@v1r_normed );

# P2 = one bondlength above Pm
my @P2 = ($Pm[0]+$bondlength*$v1r_normed[0], $Pm[1]+$bondlength*$v1r_normed[1], $Pm[2]+$bondlength*$v1r_normed[2]);

# base = base of rotating arm (along v1r_norm)
my $l = 4*$bondlength;
my @base = ($Pm[0]+$l*$v1r_normed[0], $Pm[1]+$l*$v1r_normed[1], $Pm[2]+$l*$v1r_normed[2]);

# armtoRotate is perpendicular to v1r_normed and an arbitrary 2nd axis (use x-axis) 
my @axis2 = (1,0,0);
my @armtoRotate;
_crossProduct (\@v1r_normed, \@axis2,\@armtoRotate);
_normalize( \@armtoRotate );

# rotate armtoRotate about the v1r_normed axis
my $rotateAngle=0;
for (my $r=0; $r<$nPos;$r++) {
    $rotateAngle += $angle_inc;
    my @armRotated;
    _rotateByAxisAngle (\@v1r_normed,$rotateAngle,\@armtoRotate,\@armRotated);
    my @PN = ($base[0]-$bondlength*$armRotated[0], $base[1]-$bondlength*$armRotated[1], $base[2]-$bondlength*$armRotated[2]);
    my @PC = ($base[0]+$bondlength*$armRotated[0], $base[1]+$bondlength*$armRotated[1], $base[2]+$bondlength*$armRotated[2]);
    printf "%8.3f %8.3f %8.3f %8.3f %8.3f %8.3f %8.3f %8.3f %8.3f %8.3f\n",$rotateAngle, $PN[0],$PN[1],$PN[2], $P2[0],$P2[1],$P2[2], $PC[0],$PC[1],$PC[2];
}
exit;
